# Generated by Django 3.1.7 on 2021-05-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aceservices', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=50)),
                ('street', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=20)),
                ('pincode', models.CharField(default='', max_length=50)),
                ('phoneno', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
