# Generated by Django 3.1.7 on 2021-05-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aceservices', '0008_auto_20210517_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='appliance',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='add',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
    ]
