# Generated by Django 3.1.7 on 2021-05-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aceservices', '0009_auto_20210518_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='appliance',
            field=models.CharField(choices=[('AC', 'AC'), ('Laptop', 'LAPTOP'), ('Washing Machine', 'WASHING MACHINE'), ('Computers', 'COMPUTERS'), ('Ipod', 'IPOD'), ('Mobile', 'MOBILE'), ('Fridge', 'FRIDGE'), ('Tabs', 'TABS'), ('Television', 'TELEVISION'), ('Projector', 'PROJECTOR'), ('Web Cameras', 'WEB CAMERAS'), ('Music System', 'MUSIC SYSTEM'), ('Fax Machine', 'FAX MACHINE'), ('Printers', 'PRINTERS'), ('Microwave Oven', 'MICROWAVE OVEN')], default='', max_length=20),
        ),
    ]
