# Generated by Django 3.1.7 on 2021-05-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aceservices', '0010_auto_20210518_1802'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product_table',
        ),
    ]
