# Generated by Django 3.1.7 on 2021-05-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aceservices', '0011_auto_20210519_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='payuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=30)),
            ],
        ),
    ]
